### ISSUE TITLE
Failure to read socket causes some loop

### ISSUE THREAD

**Issue by foeken** [betacooperation/agent_check#1]
```
11:50:32.365 [error] Task #PID<0.29439.5> started from #PID<0.2670.0> terminating
** (MatchError) no match of right hand side value: {:error, :closed}
    (agent_check) lib/agent_check.ex:82: AgentCheck.read_line/1
    (agent_check) lib/agent_check.ex:46: AgentCheck.serve/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.25253245/0 in AgentCheck.loop_acceptor/1>
    Args: []
```

After I while I found this message repeating over and over again. Didn't look into it yet :)

**Comment by foeken** [comment]
It seems to be an old process blocking the port
